allowBuilds:
  core-js: true
  esbuild@0.27.7: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
minimumReleaseAgeExclude:
  - '@aws-sdk/client-cloudformation@3.1146.0'
  - '@aws-sdk/client-cloudwatch-logs@3.1146.0'
  - '@aws-sdk/client-iam@3.1146.0'
  - '@aws-sdk/client-lambda@3.1146.0'
  - '@aws-sdk/client-s3@3.1146.0'
  - '@aws-sdk/client-sfn@3.1146.0'
  - '@aws-sdk/client-sts@3.1146.0'
overrides:
  vite: 'catalog:'
  vitest: 5.0.1
peerDependencyRules:
  allowAny:
    - vite
